import type { Metadata } from "next";
import "./globals.css";
import { NextProgressClient } from "./components/NextProgressClient"; 
// Initialize the Inter font

export const metadata: Metadata = {
  title: "HMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       
        <NextProgressClient /> 
        
        {/* Your existing wrapper structure */}
        <div className="flex min-h-screen">
          <main className="flex-1 bg-gray-50">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}